the-great-outdoors/grace-shopper

- server/api/blog.js
- server/api/wishlist.js
- server/db/blog.js
- server/db/index copy.js
- server/db/index.js
- server/db/seed.js
- server/db/wishlist.js
> Feature: added blog and wishlist routes

- server/api/index.js
- server/api/orders.js
- server/api/payments.js
- server/db/index.js
- server/db/orders.js
- server/db/payments.js
- server/db/seed.js
> added db and api files for orders and payments.

- server/api/index.js
- server/api/merchandise.js
- server/api/users.js
- server/api/utils.js
- server/db/seed.js
- server/db/userprefs.js
- server/db/users.js
> Features: User routes and userprefs added

- .babelrc
- src/components/CreateUserModal.js
- src/index.js
> modal update. hope it works this time

- README.md
> added next steps to read me.

- node_modules/@babel/plugin-syntax-class-properties/package.json
- package-lock.json
- package.json
- src/components/CreateUserModal.js
- src/components/Merchandise.js
- src/index.js
- webpack.config.js
Approve theses changes bro or bro-ette.
> fixed some errors to dependencies and plug-ins

- server/api/merchandise.js
- server/db/merch.js
- server/db/seed.js
- src/components/Merchandise.js
- src/components/SearchBar.js
- tests/index.spec.js
Thanks everyone for your help!
> search function working. Needs additional functionality

- src/components/Navbar.js
- src/components/SearchBar.js
- src/index.js
> fixed all the merge issues

- server/api/merchandise.js
- server/db/merch.js
- src/components/Merchandise.js
- src/components/ProductPage.js
- src/index.js
updated component ProductPage to receive selected product, populate fields with product details.
> updated product page

- server/db/merch.js
- server/db/seed.js
- src/components/Merchandise.js
- src/components/Navbar.js
- src/components/ProductPage.css
- src/components/ProductPage.js
- src/components/SearchBar.js
fixed search and category select.
> fixed search from fresh pull

- server/api/orders.js
- server/db/orders.js
- server/db/seed.js
- src/components/ProductPage.js
Please approve this when you have a chance.  Thank you!
> made changes to get checkout button working.

- server/db/seed.js
- src/components/Merchandise.js
- src/components/ProductPage.css
- src/components/ProductPage.js
> made changes to gui product page.

- server/api/wishlist.js
- server/db/seed.js
- src/components/Wishlist.js
rendering cards for wishlist path
> Feature: rendering wishlist items

- dist/index.html
- notes.txt
- server/api/blog.js
- server/api/index.js
- server/api/merchandise.js
- server/api/orders.js
- server/api/payments.js
- server/api/users.js
- server/api/wishlist.js
- server/db/blog.js
- server/db/seed.js
- server/db/users.js
- server/db/wishlist.js
- src/components/CreateUserModal.js
- src/components/EditProfile.js
- src/components/LoginModal.js
- src/components/Navbar.js
- src/components/ProductPage.js
- src/components/UserProfile.js
- src/components/index.js
- src/index.js
> adding user profile editing

- server/db/seed.js
- src/components/Cards.js
- src/components/Navbar.js
- src/components/Orders.js
- src/components/ProductPage.js
- src/components/Shipping.js
- src/components/ShippingEdit.js
- src/components/ShippingOptions.js
- src/components/index.js
- src/index.js
Please put your components for shipping and editshipping in shippingOptions component.
> added shipping and edit shipping functionality

- server/api/blog.js
- server/api/index.js
- server/api/userprefs.js
- server/api/users.js
- server/db/seed.js
- src/components/CreateUserModal.js
- src/components/EditProfile.js
- src/components/LoginModal.js
- src/components/Navbar.js
- src/components/UserProfile.js
- src/index.js
> edit profile finally works

- server/api/blog.js
- server/db/blog.js
- shipping.txt
- src/components/index.js
- src/index.js
updated blog db functions and routes
> updated blog db functions and routes

- server/api/orders.js
- src/components/Navbar.js
- src/components/Orders.js
- src/components/ProductPage.js
- src/index.js
Added OrdersPage functionality to save to orders DB and OrderItems db for logged in user
> check for user loggin. Save active cart to DB

- server/db/blog.js
- server/db/seed.js
- src/components/Navbar.js
- src/components/Orders.js
- src/components/Stories.js
- src/components/UserProfile.js
- src/index.js
> blogs working

- server/api/blog.js
- server/api/orders.js
- server/api/users.js
- server/db/blog.js
- server/db/orders.js
- server/db/seed.js
> fixed some stuff

- server/api/orders.js
- server/db/orders.js
- server/db/seed.js
- src/components/Navbar.js
- src/components/Orders.js
- src/components/Payments.js
- src/components/ProductPage.js
- src/components/ShippingEdit.js
- src/components/ShippingOptions.js
rewrote code per Justin's recommendations.
> punchout bug fixes

- server/api/blog.js
- server/db/seed.js
- src/components/ProductPage.js
- src/components/Wishlist.js
Added blogs to product page take two
> Feature: Blogs

- server/api/wishlist.js
- server/db/wishlist.js
- src/components/Cards.js
- src/components/ProductPage.js
- src/components/Wishlist.js
- src/components/index.js
> wishlist stuff is working for the most part now

- server/api/wishlist.js
- src/components/ProductPage.js
- src/components/Wishlist.js
- src/index.js
Wishlist button is hooked up in product page.
> Feature: wishlist button function

- server/api/payments.js
- src/components/AddPaymentModal.js
- src/components/EditProfile.js
- src/components/Orders.js
- src/components/ShippingOptions.js
- src/components/UserProfile.js
- src/components/index.js
- src/index.js
> design stuff and adding payment.

- src/components/Categories.js
- src/components/ShippingEdit.js
- src/components/ShippingOptions.js
- src/components/UserProfile.js
> Fixed cart forms

- src/components/ShippingOptions.js
> fixed cart forms more
